management:
  server:
    port: 8090
    ssl:
      enabled: false

server:
  http2:
    enabled: true
  ssl:
    key-store: file:etc/server.p12
    key-store-type: PKCS12
    key-store-password: 123456
    trust-store: file:etc/server-truststore.p12
    trust-store-type: PKCS12
    trust-store-password: 123456
    client-auth: need
    enabled-protocols: TLSv1.3
