management:
  server:
    ssl:
      enabled: false

server:
  http2:
    enabled: true
  ssl:
    enabled: true
    bundle: server1
    client-auth: none

spring:
  output:
    ansi:
      enabled: always
  ssl:
    bundle:
      jks:
        server1:
          key:
            alias: server
          keystore:
            location: file:etc/server.p12
            password: 123456
            type: PKCS12
          truststore:
            location: file:etc/server-truststore.p12
            password: 123456
            type: PKCS12
          options:
            enabled-protocols: [ TLSv1.3 ]
            ciphers:
              - TLS_AES_128_GCM_SHA256
              - TLS_AES_256_GCM_SHA384
              - TLS_CHACHA20_POLY1305_SHA256
        client1:
          key:
            alias: client
          keystore:
            location: file:etc/client.p12
            password: 123456
            type: PKCS12
          truststore:
            location: file:etc/client-truststore.p12
            password: 123456
            type: PKCS12
          options:
            enabled-protocols: [ TLSv1.3 ]
            ciphers:
              - TLS_AES_128_GCM_SHA256
              - TLS_AES_256_GCM_SHA384
              - TLS_CHACHA20_POLY1305_SHA256

logging:
  pattern:
    dateformat: HH:mm:ss.SSS

demo:
  ssl:
    enabled: false
    bundle: client2
