[versions]
# global versions
jdk = "25"

# dependency versions
kotlin-core = "2.3.21"
kotlin-logging = "8.0.4"
spring-boot = "4.1.0"

# plugin versions
springGradleDependencyManagement = "1.1.7"
bakdata-mockito = "2.2.0"

[libraries]
# project dependencies
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }

# test dependencies

# buildSrc dependencies (plugins)
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
kotlin-spring-gradlePlugin = { module = "org.jetbrains.kotlin.plugin.spring:org.jetbrains.kotlin.plugin.spring.gradle.plugin", version.ref = "kotlin-core" }
spring-boot-gradlePlugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot" }
spring-dm-gradlePlugin = { module = "io.spring.gradle:dependency-management-plugin", version.ref = "springGradleDependencyManagement" }
bakdata-mockito-gradlePlugin = { module = "com.bakdata.mockito:com.bakdata.mockito.gradle.plugin", version.ref = "bakdata-mockito" }

[plugins]

[bundles]
