package com.example.demo.mtls.server

import org.springframework.boot.http.client.autoconfigure.reactive.ClientHttpConnectorBuilderCustomizer
import org.springframework.boot.http.client.reactive.ReactorClientHttpConnectorBuilder

typealias ClientCustomizer = ClientHttpConnectorBuilderCustomizer<ReactorClientHttpConnectorBuilder>
